name: Run All Tests on Master Commits

on:
  push:
    branches:
      - master

jobs:
  all-tests:
    runs-on: self-hosted
    container:
        image: python:3.10-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p '*_UnitTest.py'
          python -m unittest discover -s tests -p '*_IntegrationTest.py'