
name: Run Unit Tests on Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: python:3.10-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          python -m unittest TemperatureConverter_UnitTest.py
